macros = '.macros.ts'

[[packages]]
location = 'app'
entry = 'main.ts'
environment = 'modernbrowser'

[[packages]]
location = 'bin'
entry = '*.ts'
environment = 'node'

[[packages]]
location = 'lib'
entry = '**/*.ts'
exclude = '**/*.test.ts'
environment = 'anywhere'
