macros = '.macros.ts'

[[packages]]
location = 'app'
entry = ['main.ts']
environments = ['anywhere']

[[packages]]
location = 'bin'
entry =[ '*.ts']
environments = ['node']

[[packages]]
location = 'lib'
entry = ['**/*.ts']
environments = ['anywhere']
