macros = '.macros.ts'

[[packages]]
include = 'app/main.ts'
environment = 'anywhere'

[[packages]]
include = 'bin/*.ts'
environment = 'node'

[[packages]]
include = 'lib/**/*.ts'
environment = 'anywhere'
